Box.create(:id => 1, :content_id => 2, :content_type => "BlogPost")
Box.create(:id => 32, :content_id => 32, :content_type => "BlogPost", :carousel_position => 1)
Box.create(:id => 199, :content_id => 32, :content_type => "BlogPost")
Box.create(:id => 251, :content_id => 35, :content_type => "BlogPost", :grid_position => 3)
Box.create(:id => 253, :content_id => 37, :content_type => "BlogPost", :carousel_position => 2)
Box.create(:id => 254, :content_id => 1287, :content_type => "SingleEvent", :grid_position => 1)
Box.create(:id => 255, :content_id => 1831, :content_type => "SingleEvent", :grid_position => 2)
Box.create(:id => 256, :content_id => 1330, :content_type => "SingleEvent", :grid_position => 4)
Box.create(:id => 257, :content_id => 1687, :content_type => "SingleEvent", :grid_position => 5)
Box.create(:id => 258, :content_id => 1822, :content_type => "SingleEvent", :grid_position => 6)
