Category.create(:id => 1, :title => "Social Media + Marketing", :color => "#e6007e", :podcast_category => false, :blog_category => true, :calendar_category => true)
Category.create(:id => 2, :title => "Gründerszene", :color => "#14b4e3", :podcast_category => false, :blog_category => true, :calendar_category => true)
Category.create(:id => 3, :title => "Programmieren", :color => "#A9CB38", :podcast_category => false, :blog_category => true, :calendar_category => true)
Category.create(:id => 5, :title => "Medien und Medienpädagogik", :color => "#ffed00", :podcast_category => false, :blog_category => true, :calendar_category => true)
Category.create(:id => 6, :title => "Design", :color => "#bd4ef3", :podcast_category => false, :blog_category => true, :calendar_category => true)
Category.create(:id => 7, :title => "Netzpolitik und -Aktivismus", :color => "#951b81", :podcast_category => false, :blog_category => true, :calendar_category => true)
Category.create(:id => 8, :title => "Party", :color => "#273583", :podcast_category => false, :blog_category => true, :calendar_category => true)
Category.create(:id => 10, :title => "Nerdkultur + Technologie", :color => "#b93e26", :podcast_category => false, :blog_category => true, :calendar_category => true)
Category.create(:id => 11, :title => "Gaming und digitale Kunst", :color => "#ff9039", :podcast_category => false, :blog_category => true, :calendar_category => true)
Category.create(:id => 12, :title => "Droid Boy Podcast", :color => "#888888", :podcast_category => true, :blog_category => true, :calendar_category => false, :itunes_url => "https://itunes.apple.com/de/podcast/nerdhub-podcast-droidboy/id614731100?l=en")
Category.create(:id => 13, :title => "Nerdsquad", :color => "#888888", :podcast_category => true, :blog_category => true, :calendar_category => false)
Category.create(:id => 14, :title => "NERDHUB ", :color => " #000000", :podcast_category => false, :blog_category => true, :calendar_category => false)
Category.create(:id => 15, :title => "Live-Streaming", :color => "#0cff00", :podcast_category => false, :blog_category => true, :calendar_category => true)
Category.create(:id => 16, :title => "NERDHUB Netzcast", :color => "#888888", :podcast_category => true, :blog_category => true, :calendar_category => false, :itunes_url => "https://itunes.apple.com/de/podcast/nerdhub-podcast-netzcast/id615195909?l=en")
