Picture.create(:id => 43, :title => "Anzeige - Betahaus - quadratisch", :advertisement_image => "webbanner1.jpg")
Picture.create(:id => 44, :title => "Anzeige - Betahaus - rechteckig", :advertisement_image => "webbanner2.jpg")
Picture.create(:id => 76, :title => "Anzeige - GMF - quadratisch", :advertisement_image => "railslove-ad-1.png")
Picture.create(:id => 19, :title => "Anzeige - GMF - rechteckig", :description => "Freianzeigen der Gasmotorenfabrik", :box_image => "railslove-ad-1__1_.png", :advertisement_image => "railslove-ad-1__1_.png")
Picture.create(:id => 13, :title => "Anzeige - liebhaben", :advertisement_image => "nerdhub_werbung_liebhaben.jpg")
Picture.create(:id => 17, :title => "Anzeige - Railslove - quadratich", :description => "#ad", :advertisement_image => "Untitled-4.png")
Picture.create(:id => 18, :title => "Anzeige - Railslove - rechteckig", :advertisement_image => "Untitled-5.png")
Picture.create(:id => 45, :title => "Anzeige - solution space - quadratisch", :advertisement_image => "SoulutionSeeker-Banner-02.jpg")
Picture.create(:id => 46, :title => "Anzeige - solution space - rechteckig", :advertisement_image => "SoulutionSeeker-Banner-03.jpg")
Picture.create(:id => 48, :title => "Anzeige - startplatz - quadratisch", :advertisement_image => "304x304_72dpi.jpg")
Picture.create(:id => 47, :title => "Anzeige - startplatz - rechteckig", :advertisement_image => "304x178_72dpi.jpg")
Picture.create(:id => 235, :title => "Anzeige - Termin vorschlagen", :box_image => "caroussel_terminvorschlag.jpg", :carousel_image => "caroussel_terminvorschlag.jpg")
Picture.create(:id => 88, :title => "Anzeige - UFA Lab - qudratisch", :advertisement_image => "lab_banner_304x304.jpg")
Picture.create(:id => 71, :title => "Anzeige - wealty - rechteckig", :advertisement_image => "Banner_jpg.jpg")
Picture.create(:id => 79, :title => "Artikel - AlexQDEGA", :box_image => "alexqdega_box.jpg", :carousel_image => "alexqdega_carousel.jpg")
Picture.create(:id => 94, :title => "Artikel - deploydo", :box_image => "deploydo_box.jpg")
Picture.create(:id => 209, :title => "Artikel - Lean Team Management", :box_image => "leanteam_box.jpg")
Picture.create(:id => 106, :title => "Artikel - Vidar", :box_image => "vidar_box.jpg", :carousel_image => "vidar_carousel.jpg")
Picture.create(:id => 64, :title => "Blog - rec72 5 Jahres Jubiläum", :box_image => "nerdhub_blogpodterm_rec72.jpg", :carousel_image => "nerdhub_rec72_5th.png")
Picture.create(:id => 49, :title => "Blog - Veranstalter aufgepasst!", :description => "4 Tipps für Veranstalter", :box_image => "nerdhub_blogpodterm_veranst.jpg")
Picture.create(:id => 217, :title => "Creative.Network", :box_image => "creative_network_box.jpg")
Picture.create(:id => 15, :title => "DB 51 startplatz", :box_image => "nerdhub_blog_startplatz.jpg")
Picture.create(:id => 11, :title => "DB Podcast 50", :box_image => "nerdhub_blog_50.jpg")
Picture.create(:id => 12, :title => "DB Podcast 52 Platine", :box_image => "nerdhub_blog_platine.jpg", :carousel_image => "nerdhub_carousel_db52platin.jpg")
Picture.create(:id => 74, :title => "DB Podcast 53 UFAlab", :box_image => "lab_banner_304x178.jpg")
Picture.create(:id => 128, :title => "DB Podcast 55 Startup Weekend", :box_image => "podcastDB55startupweekend_box.jpg")
Picture.create(:id => 8, :title => "Default Advertisement Picture", :advertisement_image => "url.jpeg")
Picture.create(:id => 5, :title => "Droid Boy Kopf", :box_image => "droid-boy-box.jpg")
Picture.create(:id => 9, :title => "KDDK", :description => "Werbebanner für das Feature: Klick dir deinen Kalender.", :advertisement_image => "nerdhub_werbung_homepage_kd.jpg")
Picture.create(:id => 14, :title => "nur Mut!", :advertisement_image => "nerdhub_werbung_nurmut.jpg")
Picture.create(:id => 161, :title => "Podcast - Droid Boy", :box_image => "db_podcast_box.jpg")
Picture.create(:id => 10, :title => "Railslove Anzeige", :advertisement_image => "nerdhub_werbung_railslove2.jpg")
Picture.create(:id => 214, :title => "Science Hack Day", :description => "Logo des Science Hack Days", :box_image => "5947_347478142030525_1386579273_n.jpg")
Picture.create(:id => 6, :title => "softlaunch", :box_image => "nerdhub_werbung_blogpodterm.jpg", :carousel_image => "nerdhub_beta_carousel.jpg")
Picture.create(:id => 4, :title => "test", :description => "test bild", :box_image => "box_image.png", :carousel_image => "carousel_image.png")
Picture.create(:id => 56, :title => "VA - .NET Developer Conference DDC", :box_image => "nerdhub_blogpodterm_ddc.jpg")
Picture.create(:id => 30, :title => "VA - .net User Group Köln", :box_image => "nerdhub_blogpodterm_netug.jpg")
Picture.create(:id => 107, :title => "VA - 29c3", :box_image => "29c3_box.jpg")
Picture.create(:id => 233, :title => "VA - 3DS", :box_image => "3ds_box.jpg")
Picture.create(:id => 20, :title => "VA - 4010 Lesung", :box_image => "nerdhub_blogpodterm_4010.jpg")
Picture.create(:id => 232, :title => "VA - AC.E Aachener Entrepeneurshipteam e.V.", :box_image => "ac_e_box.jpg")
Picture.create(:id => 77, :title => "VA - AdCloud", :box_image => "adcloud_box.jpg")
Picture.create(:id => 1, :title => "VA - Advance Pitching Day", :box_image => "nerdhub_blogpodterm_advpitc.jpg", :carousel_image => "nerdhub_advance_carousel2.jpg")
Picture.create(:id => 42, :title => "VA - ADVANCE Pitching Day", :box_image => "nerdhub_blogpodterm_pitchin.jpg")
Picture.create(:id => 62, :title => "VA - airbnb", :box_image => "nerdhub_blogpodterm_airbnb.jpg")
Picture.create(:id => 136, :title => "VA - Anonymous Köln", :box_image => "anonkoeln_box.jpg")
Picture.create(:id => 137, :title => "VA - Anonymous Köln - Banner 23022013", :box_image => "ano_privats_box.jpg")
Picture.create(:id => 149, :title => "VA - Bames - Digitale Spielkultur", :box_image => "bames_box.jpg")
Picture.create(:id => 80, :title => "VA - BarCamp Düren", :box_image => "bcdueren_box.jpg")
Picture.create(:id => 143, :title => "VA - betahaus Köln", :box_image => "betahausK_box.jpg")
Picture.create(:id => 148, :title => "VA - beyondtellerrand", :box_image => "beyond_tellerand_box.jpg")
Picture.create(:id => 167, :title => "VA - Bloggertreffen", :box_image => "bloggertreffen_box.jpg")
Picture.create(:id => 37, :title => "VA - Bonn Agile Meetup", :box_image => "nerdhub_blogpodterm_bonnagi.jpg")
Picture.create(:id => 119, :title => "VA - Bonn-to-code.net", :box_image => "bonntocode_box.jpg")
Picture.create(:id => 138, :title => "VA - Bottfabrik - Hacke, Fiere, Danze", :box_image => "bottfabrik_karneval_box.jpg")
Picture.create(:id => 197, :title => "VA - Braincamp", :box_image => "braincamp_css_box.jpg", :carousel_image => "braincamp_carousel_odd.jpg")
Picture.create(:id => 178, :title => "VA - Business with Soul", :box_image => "businesswithsoul_box.jpg")
Picture.create(:id => 68, :title => "VA - BVCM", :description => "Bundesverband Community Management e.V.", :box_image => "nedhub_bvcm.jpg")
Picture.create(:id => 227, :title => "VA - C'n'B", :box_image => "cnb2013_box.jpg")
Picture.create(:id => 35, :title => "VA - C4", :box_image => "nerdhub_blogpodterm_c4.jpg")
Picture.create(:id => 185, :title => "VA - CeBIT", :box_image => "cebit_box.jpg")
Picture.create(:id => 129, :title => "Va - Chaosdorf", :box_image => "chaosdorf_box.jpg")
Picture.create(:id => 219, :title => "VA - Cocoaheads Aachhen", :box_image => "cocoaheadsaacen_box.jpg")
Picture.create(:id => 216, :title => "VA - CodeSprint - Studyshare", :box_image => "study_codesprint_box.jpg")
Picture.create(:id => 70, :title => "VA - Colabor", :box_image => "nerdhub_blogpodterm_colabor.jpg")
Picture.create(:id => 36, :title => "VA - Cologne Clojure User Group", :box_image => "nerdhub_blogpodterm_clojure.jpg")
Picture.create(:id => 163, :title => "VA - Cologne Independent Game Developers Network", :box_image => "cidgn_box.jpg")
Picture.create(:id => 57, :title => "VA - cologne ITsummit_", :box_image => "nerdhub_blogpodterm_colgnei.jpg")
Picture.create(:id => 60, :title => "VA - Cologne Scene Meeting", :box_image => "colscene_klein.png", :carousel_image => "colscene_carousel.jpg")
Picture.create(:id => 33, :title => "VA - Cologne.js", :description => "http://colognejs.de/", :box_image => "nerdhub_blogpodterm_js.jpg")
Picture.create(:id => 210, :title => "VA - Cologne.pm", :box_image => "cologne_pm_box.jpg")
Picture.create(:id => 39, :title => "VA - Cologne.rb", :box_image => "nerdhub_blogpodterm_colognr.jpg")
Picture.create(:id => 99, :title => "VA - ContentMarketingConference", :box_image => "cmc_box.jpg")
Picture.create(:id => 85, :title => "VA - Crowdsourcing Summit", :box_image => "css_box.jpg")
Picture.create(:id => 108, :title => "VA - crypto party", :box_image => "cryptoparty_box.jpg")
Picture.create(:id => 212, :title => "VA - Deutscher IT-Sicherheitskongreß", :box_image => "bsi_box.jpg")
Picture.create(:id => 97, :title => "VA - Deutscher Webvideo Preis", :box_image => "wvp_box.jpg")
Picture.create(:id => 127, :title => "VA - DevHouseFriday", :box_image => "devhousefriday_box.jpg")
Picture.create(:id => 180, :title => "VA - Df | Experience Cologne", :box_image => "df_exp_cgn_box.jpg")
Picture.create(:id => 89, :title => "VA - Digital Media Women Köln", :box_image => "dmw_box.jpg")
Picture.create(:id => 157, :title => "VA - Digitales Quartett", :box_image => "digitalesquartett_box.jpg")
Picture.create(:id => 32, :title => "VA - Dingfabrik", :box_image => "nerdhub_blogpodterm_dingfab.jpg")
Picture.create(:id => 82, :title => "VA - dmexco", :box_image => "dmexco_box.jpg")
Picture.create(:id => 38, :title => "VA - dorkbot Aachen", :description => "http://hci.rwth-aachen.de/dorkbot", :box_image => "nerdhub_blogpodterm_dorkbot.jpg")
Picture.create(:id => 116, :title => "VA - Dorkbot Dingfabrik", :box_image => "dorkbot_box.jpg")
Picture.create(:id => 95, :title => "VA - dotnet cologne 2013", :box_image => "dotnet_box.jpg")
Picture.create(:id => 125, :title => "VA - Draw by Night", :box_image => "drawbynight_box.jpg")
Picture.create(:id => 205, :title => "VA - Düsseldorf on Rails", :box_image => "duesseldorf_ruby_box.jpg")
Picture.create(:id => 213, :title => "VA - ECC-Forum", :box_image => "ecc_forum_box.jpg")
Picture.create(:id => 208, :title => "VA - echtzeit Köln", :box_image => "echtzeit_box.jpg")
Picture.create(:id => 102, :title => "VA - eco", :box_image => "eco_box.jpg")
Picture.create(:id => 200, :title => "VA - eco Kongress", :box_image => "eco_kongress_box.jpg")
Picture.create(:id => 156, :title => "VA - enGAGE!", :box_image => "engage_box.jpg")
Picture.create(:id => 141, :title => "VA - EuroCIS", :box_image => "euroCIS_box.jpg")
Picture.create(:id => 81, :title => "VA - European Pirate Summit", :box_image => "eps_box.jpg")
Picture.create(:id => 92, :title => "VA - Eventgötter", :box_image => "eventgoetter_box.jpg", :carousel_image => "eventgoetter_carousel.jpg")
Picture.create(:id => 84, :title => "VA - Evoke", :box_image => "evoke_box.jpg")
Picture.create(:id => 225, :title => "Va - Evoke 2013", :box_image => "evoke2013_box.jpg")
Picture.create(:id => 139, :title => "VA - FOM Kongreß", :box_image => "fom_kongress_2_box.jpg")
Picture.create(:id => 52, :title => "VA - Forum Designrecht und designfinanzen", :box_image => "nerdhub_blogpodterm_designr.jpg")
Picture.create(:id => 222, :title => "VA - Forum Netzpolitik der KölnSPD", :box_image => "forumnetzpolitik_box.jpg")
Picture.create(:id => 175, :title => "VA - FOSSGIS", :box_image => "fossgis_box.jpg")
Picture.create(:id => 73, :title => "VA - Founderbus", :box_image => "nerdhub_blogpodterm_bus.jpg")
Picture.create(:id => 198, :title => "VA - Fraunhofer FOKUS", :box_image => "fraunhofer_box.jpg")
Picture.create(:id => 132, :title => "VA - Free Software Foundation Europe FSFE", :box_image => "fsfe_box.jpg")
Picture.create(:id => 130, :title => "VA - Freifunk", :box_image => "freifunk.jpg")
Picture.create(:id => 228, :title => "VA - Freifunk KBU", :box_image => "kbu_box.jpg")
Picture.create(:id => 199, :title => "VA - Friedrich-Ebert-Stiftung (FES)", :box_image => "fes_box.jpg")
Picture.create(:id => 96, :title => "VA - Fundraising 20 Camp", :box_image => "fundcamp20_box.jpg")
Picture.create(:id => 224, :title => "VA - Game Developer Conference Europe", :box_image => "gdceurope13_box.jpg")
Picture.create(:id => 204, :title => "VA - Games for Change Europe", :box_image => "gamesforchange_box.jpg")
Picture.create(:id => 83, :title => "VA - gamescom", :box_image => "gamescom_box.jpg")
Picture.create(:id => 134, :title => "VA - Garage Bilk", :box_image => "cowo_garagebilk_box.jpg")
Picture.create(:id => 133, :title => "VA - GarageLab", :box_image => "garagelab_duedo_box.jpg")
Picture.create(:id => 164, :title => "VA - GDG Düsseldorf", :box_image => "gtug_duesseldorf_box.jpg")
Picture.create(:id => 51, :title => "VA - geeks@cologne", :description => "Stadtbibliothekl Köln", :box_image => "nerdhub_blogpodterm_geeksat.jpg")
Picture.create(:id => 24, :title => "VA - Gesellschaft für Informatik", :description => "http://rg-koeln.gi.de", :box_image => "nerdhub_blogpodterm_gfi.jpg")
Picture.create(:id => 112, :title => "VA - Global Game Jam", :box_image => "globalgamejame_box.jpg")
Picture.create(:id => 144, :title => "VA - GplusCamp", :box_image => "gpluscamp_box.jpg")
Picture.create(:id => 234, :title => "VA - Gratis Comic Tag", :box_image => "gratiscomictag_box.jpg")
Picture.create(:id => 117, :title => "VA - GUUG German Unix User Group", :box_image => "guug_box.jpg")
Picture.create(:id => 50, :title => "VA - Hacker News CGN", :box_image => "nerdhub_blogpodterm_hncgn.jpg")
Picture.create(:id => 230, :title => "VA - hgnc", :box_image => "hgnc2_box.jpg")
Picture.create(:id => 123, :title => "VA - ICT", :box_image => "ict_box.jpg")
Picture.create(:id => 215, :title => "VA - IHK Düsseldorf", :box_image => "IHK_DUESSEL_box.jpg")
Picture.create(:id => 154, :title => "VA - IHK Köln", :box_image => "ihkkoeln_box.jpg")
Picture.create(:id => 140, :title => "VA - IHK NRW", :box_image => "ihkNRW_box.jpg")
Picture.create(:id => 114, :title => "VA - imm Bloggertreffen 2013", :box_image => "immBloggertreffem_box.jpg")
Picture.create(:id => 223, :title => "VA - imt13", :box_image => "imt13_box.jpg")
Picture.create(:id => 58, :title => "VA - insidrr", :box_image => "nerdhub_blogpodterm_insidrr.jpg", :carousel_image => "carousel_insidrrr.jpg")
Picture.create(:id => 195, :title => "VA - Instawalk 23_3_2013", :box_image => "instawalk_23_3_2013_box.jpg")
Picture.create(:id => 87, :title => "VA - Intel Extreme Masters", :box_image => "intelextrememasters_box.jpg")
Picture.create(:id => 170, :title => "VA - Interactive Cologne", :box_image => "nerdhub_blogpodterm_geeksat.png", :carousel_image => "interactive_nerdhub.png")
Picture.create(:id => 201, :title => "VA - Internationale Filmschule (IFS)", :box_image => "ifs_box.jpg")
Picture.create(:id => 110, :title => "VA - Joomla! User Group CGN", :box_image => "jugc_box.jpg")
Picture.create(:id => 184, :title => "VA - Kanban Konferenz", :box_image => "lwipcgn_box.jpg")
Picture.create(:id => 75, :title => "VA - KIUBJU Grillen", :box_image => "kiubju_box.jpg")
Picture.create(:id => 191, :title => "VA - Köln API", :box_image => "koelnapi_box.jpg")
Picture.create(:id => 135, :title => "VA - Köln R User Group", :box_image => "rug_box.jpg")
Picture.create(:id => 29, :title => "VA - KölnDesign", :description => "http://koelndesign.de", :box_image => "nerdhub_blogpodterm_kd.jpg")
Picture.create(:id => 122, :title => "VA - KölnDesign - Let's talk about design", :box_image => "letstalkaboutdesign_box.jpg")
Picture.create(:id => 147, :title => "VA - Kölner Forum Medienrecht", :box_image => "koelnerofurm_medienrecht_box.jpg")
Picture.create(:id => 101, :title => "VA - Kölner Themenjahr - Flug- und Raumfahrt", :box_image => "koelnthemenjahr_box.jpg")
Picture.create(:id => 179, :title => "VA - Kongress CREATIVE.Arbeit", :box_image => "creativearbeit_box.jpg")
Picture.create(:id => 41, :title => "VA - Landesanstalt für Median LFM", :box_image => "nerdhub_blogpodterm_lfm.jpg")
Picture.create(:id => 16, :title => "VA - LastTuesday", :box_image => "nerdhub_term_kiult.jpg")
Picture.create(:id => 181, :title => "VA - Lean Coffee Cologne", :box_image => "cgnleancoffee_box.jpg")
Picture.create(:id => 153, :title => "VA - Learn with Google", :box_image => "learnwithgoogle_box.jpg")
Picture.create(:id => 151, :title => "VA - Limited WIP Society Köln", :box_image => "limitedWIP_box.jpg")
Picture.create(:id => 31, :title => "VA - Linux Workshop Köln", :box_image => "nerdhub_blogpodterm_linuxwo.jpg")
Picture.create(:id => 207, :title => "VA - Löt IT!", :box_image => "loetit_box.jpg")
Picture.create(:id => 193, :title => "VA - Medienfrauen NRW", :box_image => "medienfrauen_box.jpg")
Picture.create(:id => 173, :title => "VA - Minikonferenz", :box_image => "minikonferenz_box.jpg", :carousel_image => "nerdhub-large__3_.gif")
Picture.create(:id => 187, :title => "VA - Minikonferenz live", :box_image => "minikonferenz_live_box.jpg", :carousel_image => "carousel_minikonferenz_live.jpg")
Picture.create(:id => 53, :title => "VA - MMT", :box_image => "nerdhub_blogpodterm_mmt.jpg")
Picture.create(:id => 54, :title => "VA - MMT 32", :description => "Photopraktika", :box_image => "nerdhub_blogpodterm_mm32.jpg")
Picture.create(:id => 152, :title => "VA - Mobile World Congress TV", :box_image => "mobileworld_box.jpg")
Picture.create(:id => 26, :title => "VA - mobile.cologne", :description => "http://www.mobilecologne.de/", :box_image => "nerdhub_blogpodterm_mobilec.jpg")
Picture.create(:id => 145, :title => "VA - monitoringcamp", :box_image => "monitoringcamp_box.jpg")
Picture.create(:id => 103, :title => "VA - Museum Ludwig", :box_image => "museumludwig_box.jpg")
Picture.create(:id => 150, :title => "VA - NERDHUB Netzcast", :box_image => "nerdhub_netzcast_box.jpg")
Picture.create(:id => 22, :title => "VA - Next Level", :description => "http://www.nextlevel-conference.org/", :box_image => "nerdhub_blogpodterm_nextlev.jpg")
Picture.create(:id => 25, :title => "VA - NoSQL Group CGN", :description => "http://www.nosql-cologne.org/", :box_image => "nerdhub_blogpodterm_nosql.jpg")
Picture.create(:id => 221, :title => "VA - NoSQL matters", :box_image => "nosqlmatters_box.jpg")
Picture.create(:id => 211, :title => "VA - ODL Düesseldorf", :box_image => "odl_duessel_box.jpg")
Picture.create(:id => 93, :title => "VA - one day on earth", :box_image => "onedayonearth.jpg")
Picture.create(:id => 111, :title => "VA - Online Marketing Friday", :box_image => "omf_box.jpg")
Picture.create(:id => 66, :title => "VA - Open Data Day Köln", :box_image => "opendatadaykoeln_box.jpg", :carousel_image => "carousel_odd.jpg")
Picture.create(:id => 176, :title => "VA - Open Data Day Köln LIVE!", :box_image => "opendatadaykoeln_box.jpg", :carousel_image => "odd_live_carousel.jpg")
Picture.create(:id => 194, :title => "VA - Open Ruhr", :box_image => "openuhr_box.jpg")
Picture.create(:id => 160, :title => "Va - Open Street Map", :box_image => "osm_box.jpg")
Picture.create(:id => 186, :title => "VA - OpenNRW", :box_image => "opennrw_box.jpg")
Picture.create(:id => 115, :title => "VA - OpenStack Community Abend", :box_image => "openstack_box.jpg")
Picture.create(:id => 28, :title => "VA - OSK", :description => "http://koeln.online-stammtisch.com/", :box_image => "nerdhub_blogpodterm_osk.jpg")
Picture.create(:id => 182, :title => "VA - PASS", :box_image => "pass_box.jpg")
Picture.create(:id => 113, :title => "VA - Passagen", :box_image => "passagen_box.jpg")
Picture.create(:id => 61, :title => "VA - Pecha Kucha Köln", :box_image => "nerdhub_blogpodterm_pechaku.jpg")
Picture.create(:id => 168, :title => "VA - Pecha Kucha Night Düsseldorf", :box_image => "pechakucha_duess_box.jpg")
Picture.create(:id => 34, :title => "VA - pycologne", :description => "http://wiki.python.de/pycologne/", :box_image => "nerdhub_blogpodterm_pycgn.jpg")
Picture.create(:id => 91, :title => "VA - pycon", :box_image => "pycon_box.jpg")
Picture.create(:id => 86, :title => "VA - Python Camp", :box_image => "pythoncamp_box.jpg")
Picture.create(:id => 203, :title => "VA - Python Meeting Düsseldorf", :box_image => "pyduesseldorf_box.jpg")
Picture.create(:id => 171, :title => "VA - Python Software Verband", :box_image => "pythonsoftwareverband_box.jpg")
Picture.create(:id => 131, :title => "VA - pythonfoo", :box_image => "pythonfoo_box.jpg")
Picture.create(:id => 69, :title => "VA - Qdega", :box_image => "nedhub_qdega.jpg")
Picture.create(:id => 206, :title => "VA - Quantified Self Köln ", :box_image => "qs_koeln_box.jpg")
Picture.create(:id => 174, :title => "VA - Rails Girls Rheinland", :box_image => "rg_rheinland_box.jpg")
Picture.create(:id => 23, :title => "VA - Railsgirls CGN", :box_image => "railsgirls_cgn.jpg")
Picture.create(:id => 169, :title => "VA - rheinjug", :box_image => "rheinjug_box.jpg")
Picture.create(:id => 229, :title => "VA - Rheinland-Pitch", :box_image => "rheinlandpitch_box.jpg")
Picture.create(:id => 142, :title => "VA - Safer Internet Day", :box_image => "sid_box.jpg")
Picture.create(:id => 90, :title => "VA - Security Check - Stefan Thull", :box_image => "thillsecurity_box.jpg")
Picture.create(:id => 109, :title => "VA - SIGINT 2013", :box_image => "sigint2013_box.jpg")
Picture.create(:id => 202, :title => "VA - SMCBN", :box_image => "smcbn_box.jpg")
Picture.create(:id => 105, :title => "VA - social community day", :box_image => "socialcommunityday_box.jpg")
Picture.create(:id => 188, :title => "VA - Social Media Anwenderkonferenz", :box_image => "smanwenderkonferenz_box.jpg")
Picture.create(:id => 104, :title => "VA - Social Web Breakfast", :box_image => "socialbreakfast_box.jpg")
Picture.create(:id => 67, :title => "VA - socialbar köln", :description => "http://socialbar.de/wiki/Koeln", :box_image => "nedhub_socialbar.jpg")
Picture.create(:id => 177, :title => "VA - Softwerkskammer", :box_image => "softwerkskammer_box.jpg")
Picture.create(:id => 72, :title => "VA - Solution Events", :box_image => "nerdhub_blogpodterm_solutio.jpg")
Picture.create(:id => 118, :title => "VA - Solution Space 2.0", :box_image => "solutionspace_box.jpg", :carousel_image => "solutionspace20_carousel.jpg")
Picture.create(:id => 231, :title => "VA - Spring Thing", :box_image => "apringthing_box.jpg")
Picture.create(:id => 55, :title => "VA - Stadt Köln", :box_image => "nerdhub_blogpodterm_stadtk_.jpg")
Picture.create(:id => 21, :title => "VA - Startplatz", :description => "Inkubator im Mediapark.", :box_image => "nerdhub_blogpodterm_startpl.jpg")
Picture.create(:id => 155, :title => "VA - STARTPLATZ Events - Gunter Dueck", :box_image => "startplatz_box.jpg", :carousel_image => "dueckvortragsreihe_dueck.jpg")
Picture.create(:id => 63, :title => "VA - StartUp Breakfast", :box_image => "nerdhub_blogpodterm_startup.jpg")
Picture.create(:id => 124, :title => "VA - Startup Safari", :box_image => "safari_box.jpg")
Picture.create(:id => 98, :title => "VA - Startup Weekend NEXT", :box_image => "next_box.jpg")
Picture.create(:id => 78, :title => "VA - StartupWeekendCGN", :box_image => "startupweekend_box.jpg", :carousel_image => "Untitled-2.jpg")
Picture.create(:id => 189, :title => "VA - switch Asia", :box_image => "switchasia_box.jpg")
Picture.create(:id => 162, :title => "VA - Symfony Usergroup Köln", :box_image => "symfonyUGcgn_box.jpg")
Picture.create(:id => 226, :title => "Va - SymfonySummit", :box_image => "symfony_summit_box.jpg")
Picture.create(:id => 121, :title => "VA - TUGCGN", :box_image => "tugcgn_box.jpg")
Picture.create(:id => 146, :title => "VA - tweetcamp", :box_image => "tweetcamp_box.jpg")
Picture.create(:id => 65, :title => "VA - Twittagessen", :box_image => "nerdhub_blogpodterm_twittag.jpg")
Picture.create(:id => 59, :title => "VA - Twittwoch Köln", :box_image => "twitteoch_box.jpg")
Picture.create(:id => 183, :title => "VA - UX-CGN", :box_image => "uxcgn_box.jpg")
Picture.create(:id => 192, :title => "VA - VDE ", :box_image => "vde_box.jpg")
Picture.create(:id => 158, :title => "VA - VHS Einmischen ", :box_image => "vhs_einmischen_box.jpg")
Picture.create(:id => 40, :title => "VA - Web De Cologne", :box_image => "nerdhub_blogpodterm_webdeco.jpg")
Picture.create(:id => 218, :title => "VA - webcon 2013", :box_image => "webcon2013_box.jpg")
Picture.create(:id => 172, :title => "VA - Webgrrls NRW", :box_image => "webggrrls_nrw_box.jpg")
Picture.create(:id => 196, :title => "VA - Webmontag Bonn", :box_image => "webmontag_bonn_box.jpg")
Picture.create(:id => 165, :title => "VA - Webworker Ruhr", :box_image => "wwruhr_box.jpg")
Picture.create(:id => 159, :title => "VA - Wikipedia Stammtisch Köln", :box_image => "wikipedia_box.jpg")
Picture.create(:id => 190, :title => "VA - Windows 8 Hackathon", :box_image => "win8hackathon_box.jpg", :carousel_image => "win8hackathon_carousel.jpg")
Picture.create(:id => 100, :title => "VA - Wissenschaft im Rathaus", :box_image => "kwir_box.jpg")
Picture.create(:id => 166, :title => "VA - Wissensdurst", :box_image => "wissensdurst_box.jpg")
Picture.create(:id => 220, :title => "VA - World Plone Day", :box_image => "worldploneday_box.jpg")
Picture.create(:id => 27, :title => "VA - World Usability Day 2012", :description => "http://worldusabilityday.de/groups/koeln", :box_image => "nerdhub_blogpodterm_wud12.jpg")
Picture.create(:id => 126, :title => "VA - XING Regionalgruppe Köln", :box_image => "xing_koeln_box.jpg")
Picture.create(:id => 120, :title => "VA - Zukunftswerkstatt", :box_image => "zukunmftswerkstatt_box.jpg")
Picture.create(:id => 7, :title => "werbung", :description => "tset", :advertisement_image => "box_image.png")
